defaults:
  - clips: final_dataset
  - preprocess: qwen3
  - extract_geometry: qwen3
  - track_objects: qwen3
  - graph_extraction: precomputed_qwen3
  - eval: default
  - compute_metrics: default
  - _self_
  
cholecseg8k_root: data/cholecseg8k

preprocessed_root: data/preprocessed/clean
output_root: output/clean

config_dumps:
  # - ${output_root}/config.yaml

hydra:
  job:
    chdir: false